"""ClaimScene CLI — the judge-runnable offline proof.

    python -m claimscene.cli --case demo --photos sample-photos --out out

Runs the full pipeline offline (no credentials, no network): photos →
constrained scene graph → deterministic schematic (SVG + PNG + MP4 when
ffmpeg is present) → illustration clip (offline fake unless live adapters
are wired) → report → sealed manifest. Prints per-artifact SHA-256
verification at the end. When ``--photos`` is missing or empty, three tiny
synthetic photos are generated (source = synthetic_generated), so the demo
never needs real imagery.
"""
from __future__ import annotations

import argparse
import io
import sys
from pathlib import Path

from .case import CasePhoto, CaseSpec, PhotoRole, PhotoSource
from .config import build_extractor, build_provider, build_storage, mode
from .provenance import verify_artifact, verify_manifest

_EXTENSIONS = {".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg",
               ".webp": "image/webp", ".bmp": "image/bmp"}

_OUT_FILES = {
    "scene_graph": "scene.json",
    "timeline": "timeline.json",
    "schematic_svg": "schematic.svg",
    "schematic_hero": "schematic.png",
    "schematic_animation": "schematic.mp4",
    "illustration_still": "illustration.png",
    "illustration": "illustration.mp4",
    "report": "report.md",
    "manifest": "manifest.json",
}


def _infer_role(filename: str) -> PhotoRole:
    lower = filename.lower()
    if "damage" in lower:
        return PhotoRole.damage_photo
    if "road" in lower:
        return PhotoRole.road_photo
    return PhotoRole.scene_photo


def _load_photos(photos_dir: Path, source: PhotoSource) -> list[CasePhoto]:
    if not photos_dir.is_dir():
        return []
    photos: list[CasePhoto] = []
    for path in sorted(photos_dir.iterdir()):
        media_type = _EXTENSIONS.get(path.suffix.lower())
        if media_type is None or not path.is_file():
            continue
        photos.append(CasePhoto(filename=path.name, data=path.read_bytes(),
                                media_type=media_type, role=_infer_role(path.name),
                                source=source))
    return photos


def _synthetic_photos() -> list[CasePhoto]:
    """Three tiny deterministic PNGs so the demo runs with zero real imagery."""
    from PIL import Image, ImageDraw

    specs = [("scene_overview.png", PhotoRole.scene_photo, (36, 52, 66)),
             ("damage_closeup.png", PhotoRole.damage_photo, (66, 40, 36)),
             ("road_context.png", PhotoRole.road_photo, (38, 60, 44))]
    photos: list[CasePhoto] = []
    for name, role, rgb in specs:
        img = Image.new("RGB", (320, 240), rgb)
        draw = ImageDraw.Draw(img)
        draw.rectangle([8, 8, 311, 231], outline=(200, 210, 220))
        draw.text((16, 16), f"STAGED DEMO INPUT\n{name}", fill=(220, 230, 240))
        buf = io.BytesIO()
        img.save(buf, format="PNG")
        photos.append(CasePhoto(
            filename=name, data=buf.getvalue(), media_type="image/png", role=role,
            source=PhotoSource.synthetic_generated,
            attribution="generated by the claimscene demo CLI",
            license="CC0-1.0",
        ))
    return photos


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="claimscene",
        description="Honest accident documentation & illustration (offline by default)",
    )
    parser.add_argument("--case", default="demo", help="case id (default: demo)")
    parser.add_argument("--photos", default=None,
                        help="directory of input photos (omit to use synthetic demo inputs)")
    parser.add_argument("--out", default="out", help="output directory (default: out)")
    parser.add_argument("--context", default=None,
                        help="optional free-text context passed to the extractor")
    parser.add_argument("--source", default=PhotoSource.staged_demo.value,
                        choices=[s.value for s in PhotoSource],
                        help="provenance source recorded for loaded photos")
    args = parser.parse_args(argv)

    try:  # keep output readable regardless of the Windows console code page
        sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[union-attr]
    except Exception:
        pass

    photos: list[CasePhoto] = []
    if args.photos:
        photos = _load_photos(Path(args.photos), PhotoSource(args.source))
    if not photos:
        print("no input photos found; generating synthetic demo inputs")
        photos = _synthetic_photos()

    # Local import keeps CLI startup cheap for --help.
    from .pipeline import CasePipeline

    pipeline = CasePipeline(build_extractor(), build_provider(), build_storage())
    spec = CaseSpec(case_id=args.case, photos=photos, context=args.context)
    result = pipeline.run(spec)

    out_dir = Path(args.out) / args.case
    out_dir.mkdir(parents=True, exist_ok=True)
    for name, filename in _OUT_FILES.items():
        if name in result.payloads:
            (out_dir / filename).write_bytes(result.payloads[name])
    index = getattr(pipeline.storage, "index_jsonl", None)
    if callable(index):
        (out_dir / "index.jsonl").write_text(index() + "\n", encoding="utf-8")

    print(f"\nCLAIMSCENE case '{args.case}'  (mode={mode()}, "
          f"provider={result.provider_name}, degraded={result.degraded})")
    print(f"  inputs           : {len(photos)} photo(s), sources="
          f"{sorted({p.source.value for p in photos})}")
    for name in _OUT_FILES:
        ref = result.artifacts.get(name)
        if ref:
            print(f"  {name:<17}: {ref.sha256[:16]}…  {ref.size_bytes:>8} B  -> "
                  f"{out_dir / _OUT_FILES[name]}")
    if "schematic_animation" not in result.artifacts:
        print("  schematic_animation: skipped (ffmpeg not found)")

    print("\nverification")
    ok = verify_manifest(result.manifest)
    print(f"  manifest seal          : {'PASS' if ok else 'FAIL'}")
    checks = ["scene_graph", "timeline", "report", "illustration",
              "illustration_still", "schematic_svg", "schematic_hero"]
    if "schematic_animation" in result.artifacts:
        checks.append("schematic_animation")
    for name in checks:
        good = verify_artifact(result.manifest, name, result.payloads[name])
        ok = ok and good
        print(f"  {name:<23}: {'PASS' if good else 'FAIL'}")
    print(f"\nVERIFY: {'PASS' if ok else 'FAIL'}  "
          f"(manifest_hash={result.manifest_hash[:16]}…)")
    return 0 if ok else 1


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
