from claimscene.adapters.fakes import _scene_left_cross, _scene_rear_end
from claimscene.layout import LayoutEngine
from claimscene.provenance import DISCLOSURE
from claimscene.report import build_report, illustration_prompt, illustration_still_prompt


def test_report_is_deterministic_and_carries_disclosure():
    scene = _scene_rear_end()
    timeline = LayoutEngine().build(scene)
    a = build_report(scene, timeline, case_id="case-9")
    b = build_report(scene, timeline, case_id="case-9")
    assert a == b
    assert "case-9" in a
    assert DISCLOSURE in a


def test_report_speaks_the_vocabulary_in_words():
    scene = _scene_rear_end()
    timeline = LayoutEngine().build(scene)
    report = build_report(scene, timeline, case_id="c")
    assert "6 o'clock (rear)" in report
    assert "12 o'clock (front)" in report
    assert "a traffic light" in report
    assert "blue car" in report and "red car" in report
    assert "stopped" in report


def test_report_includes_confidence_notes_and_extras():
    scene = _scene_left_cross()
    scene.confidence_notes.append("photo 2 was blurry")
    timeline = LayoutEngine().build(scene)
    report = build_report(scene, timeline, case_id="c",
                          extra_notes=["illustration generated by 'fake-media'"])
    assert "## Confidence notes" in report
    assert "photo 2 was blurry" in report
    assert "fake-media" in report


def test_illustration_prompt_deterministic_and_self_disclosing():
    scene = _scene_left_cross()
    a = illustration_prompt(scene)
    assert a == illustration_prompt(scene)
    assert DISCLOSURE in a
    assert "silver toy car" in a and "green toy van" in a
    assert "non-photorealistic" in a


def test_prompts_stay_in_the_moderation_safe_diorama_register():
    """Both generation prompts must keep the toy-diorama framing
    (probe-verified to pass content moderation) and depict no people."""
    scene = _scene_rear_end()
    for prompt in (illustration_still_prompt(scene), illustration_prompt(scene)):
        assert "Miniature diecast toy car diorama" in prompt
        assert "no people, no injuries" in prompt
        assert "non-photorealistic" in prompt


def test_still_prompt_describes_vehicles_and_damage():
    scene = _scene_rear_end()
    a = illustration_still_prompt(scene)
    assert a == illustration_still_prompt(scene)
    assert "blue toy car" in a and "red toy car" in a
    assert "crush mark at its 6 o'clock (rear)" in a
    assert DISCLOSURE not in a  # the overlay instruction belongs to the clip
